### ISSUE TITLE
ExoPlayer should handle media button events

### ISSUE THREAD

**Issue by Maxr1998** [jellyfin/jellyfin-android-next#9]
Play/pause events from e.g. headphones should be dispatched to ExoPlayer

**Comment by neopc10** [comment]
Do you have any intention of adding next/previous video via headset [onSkipToNext(), onSkipToPrevious()] if the user has multiple items queued? Furthermore, more abstractly, anything about voice actions invoked while ExoPlayer is running and when it is not? The latter would be focusing specifically on voice search results.

**Comment by Maxr1998** [comment]
Voice actions for the handled actions should already work, voice actions to initiate playback would be rather complicated I fear. Maybe sometime in the future, but not a high priority. Previous/next could be added once we have real queuing support within the webapp. That's an upstream thing though. I'd suggest you to file separate issues for these points, as they don't relate as closely to the current issue.
